name: Main CI runs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
      - name: Install dependencies
        run: npm ci

  # Prettier checks job
  prettier-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test prettier diff
        run: npx --no-install prettier --check .
